imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       86400

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: UserScan\ContentBundle\Controller\ExceptionController::showAction
    globals:
          project_task_max_count: %project_task_max_count%

services:
    twig.extension.txt:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    common_monolog_processor:
            class: UserScan\ContentBundle\MonologExtension\MonologProcessor
            tags:
                - { name: monolog.processor, handler: swift }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
# @todo Configure UserScan Domain Email with Swiftmailer Spool Service
swiftmailer:
    transport:  %mailer_transport%
    #encryption: %mailer_encryption%
    #auth_mode:  %mailer_auth_mode%
    #host:       %mailer_host%
    #port:       %mailer_port%
    username:   %mailer_user%
    password:   %mailer_password%


jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

parameters:
    video_path:   %kernel.root_dir%/../videos/
    video_target: %kernel.root_dir%/../web/videos/

    project_task_max_count: 6