imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
framework:
    router:
        strict_requirements: null

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error #error
            handler:      grouped #nested
        #nested:
        #    type:  stream
        #    path:  %kernel.logs_dir%/%kernel.environment%.log
        #    level: debug
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:   stream
            path:   %kernel.logs_dir%/%kernel.environment%.log
            level:  debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: contact@userscan.com
            to_email:   miniyarov@gmail.com
            subject:    A Critical (500) Error Report
            level:      debug