parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: ~
    database_name: userscan
    database_user: root
    database_password: pont

    #@todo Configure Local SMTP
    #mailer_transport: "smtp"
    #mailer_host: "mail.userscan.com"
    #mailer_user: "contact@userscan.com"
    #mailer_password: "UserScanContact*.*2012"
    #mailer_encryption: "ssl"
    #mailer_auth_mode: "login"
    #mailer_port: "25"

    #using gmail for dev env
    mailer_transport: gmail
    mailer_user: userscan@gmail.com
    mailer_password: usc'10131013

    locale: tr
    secret: c1b6a9610c7f2831fd935ab1eba05ed3a