UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

ProjectBundle:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /

ContentBundle:
    resource: "@ContentBundle/Resources/config/routing.yml"
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
