_homepage:
    pattern:  /
    defaults: { _controller: ContentBundle:Content:index }

project_tester:
    pattern: /project/{url_id}/
    defaults: { _controller: ContentBundle:Tester:index }
    requirements:
        url_id: ([a-z0-9]+)

project_xml:
    pattern: /project_xml/{url_id}/
    defaults: { _controller: ContentBundle:Tester:xmlGenerator }
    requirements:
        url_id: ([a-z0-9]+)

project_file_upload:
    pattern: /video_up/{project_id}/{tester_id}/
    defaults: { _controller: ContentBundle:Upload:handle }
    requirements:
        _method: POST

how_it_works:
    pattern: /nasil-calisir/
    defaults: { _controller: ContentBundle:Content:howItWorks }

about:
    pattern: /hakkimizda/
    defaults: { _controller: ContentBundle:Content:about }

services:
    pattern: /servisler/
    defaults: { _controller: ContentBundle:Content:services }

blog:
    pattern: /blog/
    defaults: { _controller: ContentBundle:Content:blog }

contact:
    pattern: /iletisim/
    defaults: { _controller: ContentBundle:Content:contact }

prices:
    pattern: /fiyatlar/
    defaults: { _controller: ContentBundle:Content:prices }